### ISSUE TITLE
list: listing all the detail info for the target blocks will make sense ?

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#153]
Currently the gluster-block list will only list the target block names, and there are more detail info such as the priopath, size, HA number... Will this make sense here ?

@pkalever @amarts

**Comment by lxbsz** [comment]
Yeah, make sense and the following is just one simple idea, we may need more options ? Or just adjust it to be more backward compatible.
 
```
 list    <volname> [OPTION]
        list available block devices.
        OPTIONS:
        -l:  use a long listing format
        -r:  ringbuffer size
        -s:  target block size
        -S:  target block size in human-readable format
        -h:  HA number
        -g:  GBID
        -p:  priopath

```

**Comment by pkalever** [comment]
@lxbsz we have info command to get the additional details. In that case, why do we need to furnish details with list command ? see '# gluster vol list' output

Currently list command output is fetched in one rpc reply from daemon's cli thread, and there are limitations with the rpc reply buffer (may be 4M, not sure), which is why we kept it minimal. See https://bugzilla.redhat.com/show_bug.cgi?id=1454412

I understand this is an bonus feature, but I feel we should first fix BZ#1454412, and then fall here.

Thanks!

**Comment by lxbsz** [comment]
I was thinking it should be more friendly if we can list all the detail info for all the blocks at one time.

Currently the info command need to list them one by one.

**Comment by pkalever** [comment]
> I was thinking it should be more friendly if we can list all the detail info for all the blocks at one time.
> 
> Currently the info command need to list them one by one.

For this, we need to fix https://bugzilla.redhat.com/show_bug.cgi?id=1454412 first.

**Comment by lxbsz** [comment]
> > I was thinking it should be more friendly if we can list all the detail info for all the blocks at one time.
> > Currently the info command need to list them one by one.
> 
> For this, we need to fix https://bugzilla.redhat.com/show_bug.cgi?id=1454412 first.

Yeah, make sense.

**Comment by pkalever** [comment]
I would like to leave it as it is for now. Feel free to open it later if needed. Thanks!
