### ISSUE TITLE
Auditing of gluster-block commands

### ISSUE THREAD

**Issue by vbellur** [gluster/gluster-block#22]
Need a file / mechanism to log all requests that gluster-block daemon receives. It would be good to log the network identity of the requestor along with details about the request. Logging response status of requests received would be needed as well.

**Comment by bhumikagoyal** [comment]
Workflow as discussed with @pranithk 

Before arriving at the solution, we considered two ways of how logging the responses can be done:
 1.  Logging at the CLI component at the end.
 2.  Logging at the CLI thread of gluster-blockd.

Logging at the CLI component at the end:
After receiving and collecting the responses from all the hosts, gluster-blockd sends the final response to the CLI. This final response can be logged at CLI. But what if the CLI process is aborted in between of execution. In this case gluster-blockd won't be able to contact the CLI and responses can't be logged.
So, logging at the CLI thread of gluster-blockd would be a better approach.

Solution:
Logging at the CLI thread of gluster-blockd.
Log the response as soon as the CLI thread receives the response from the server. Because the CLI thread keeps running in the background, we can still log the responses even if the command line process is stopped.
The format of logging can be like:
<CLI command>:  SUCCESS: <out response string>
<CLI command>:  FAILURE: <out response string>

Right now we have all the above information except the CLI command. For storing the CLI command we can create a field in the structures block{Create/Delete/Modify}Cli.
In this way we can know what command got executed, success/failure on each host and the reason.

@pkalever @lxbsz  Please suggest any improvements/corrections.

**Comment by lxbsz** [comment]
@bhumikagoyal 

This looks good to record and collect all logs of the request, it will be very useful for us to trouble shoot the bugs.

Should we also log the status whether the gluster-blockd side has received the request or not in gluster-blockd side ?

**Comment by amarts** [comment]
#83 fixes this right? Should we close this?

**Comment by pkalever** [comment]
Fixed-by: https://github.com/gluster/gluster-block/pull/83
