### ISSUE TITLE
Correct gluster block size calculation based on the unit string.

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-block#44]
At present, if we specify `Gb` or `GiB`, glusterblock utility calculates the space in `1024` mebibytes where it should be `1000` in case of `GB` and `1024` incase of `GiB". https://github.com/gluster/gluster-block/blob/master/utils/common.c#L78 .  More details on this spec can be found @ https://en.wikipedia.org/wiki/Gibibyte.  This is not correct and user expects the correct calculation in gluster block based on the unit specified.

**Comment by obnoxxx** [comment]
More precisely, anything starting with a "G" is treated as (1024)^3 by gluster-block. I'e `1Grand` and `1GiB` and `1G` and `1Github` will all result in the same. The only thing that the gluster-block manpage documents is GiB. So that's what is supported today. We should make the input-checking some more strict and only allow GiB, TiB etc. We *could* also allow G, T, etc as single letter size units for these, as there is no standard meaning for this anyways.

And finally, we should improve the error message in https://github.com/gluster/gluster-block/blob/master/utils/common.c#L95 to mention gibibytes etc instead of gigabytes.

One should acknowledge though that the wikipedia article cited mentions that the use of gigabytes vs gibibytes is not universally accepted. (https://www.ahdictionary.com/word/search.html?id=G5128100) There have been lawsuits due to this lack of common understanding.

The same topic is also currently discussed in https://github.com/kubernetes-incubator/external-storage/pull/496.

**Comment by obnoxxx** [comment]
@pranithk @pkalever fyi

**Comment by obnoxxx** [comment]
FYI: just proposed a RP to heketi to be more precise in the documentation and messages about using GiB: https://github.com/heketi/heketi/pull/935

**Comment by pkalever** [comment]
As @obnoxxx mentioned it right. Right now gluster-block support only GiB patterns, anything like G or Gi or GXZ is treated as GiB only. 

It will be good to bring more strict checks about requested units. It is clear for me that we should interpret GB as 1000^3 and GiB as 1024^3, but we need to also define what is G ? i.e GB or GiB

@obnoxxx @humblec @vbellur @pranithk  Thoughts ?

**Comment by obnoxxx** [comment]
@pklever my proposal is keep it simple: only support powers of 1024. Lock down the parsing to support KiB, MiB, GiB etc, and keep K, M, G etc as synonyms since that may already have been used. (As mentioned this also matches what programs like "dd" do.) Fail on all other inputs. (GB, Gluster, ...)

**Comment by obnoxxx** [comment]
@pkalever patch proposed to implement the same: https://review.gluster.org/19027
